// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FrameSync.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from FrameSync.proto</summary>
public static partial class FrameSyncReflection {

  #region Descriptor
  /// <summary>File descriptor for FrameSync.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FrameSyncReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9GcmFtZVN5bmMucHJvdG8iQwoIRnJhbWVScGMSEgoKbWV0aG9kSGFzaBgB",
          "IAEoBRITCgtiZWhhdmlvcklkeBgCIAEoBRIOCgZwYXJhbXMYAyABKAxiBnBy",
          "b3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::FrameRpc), global::FrameRpc.Parser, new[]{ "MethodHash", "BehaviorIdx", "Params" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 帧同步消息
/// </summary>
public sealed partial class FrameRpc : pb::IMessage<FrameRpc>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FrameRpc> _parser = new pb::MessageParser<FrameRpc>(() => new FrameRpc());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<FrameRpc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FrameSyncReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FrameRpc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FrameRpc(FrameRpc other) : this() {
    methodHash_ = other.methodHash_;
    behaviorIdx_ = other.behaviorIdx_;
    params_ = other.params_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FrameRpc Clone() {
    return new FrameRpc(this);
  }

  /// <summary>Field number for the "methodHash" field.</summary>
  public const int MethodHashFieldNumber = 1;
  private int methodHash_;
  /// <summary>
  /// 方法hash
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int MethodHash {
    get { return methodHash_; }
    set {
      methodHash_ = value;
    }
  }

  /// <summary>Field number for the "behaviorIdx" field.</summary>
  public const int BehaviorIdxFieldNumber = 2;
  private int behaviorIdx_;
  /// <summary>
  /// 行为id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int BehaviorIdx {
    get { return behaviorIdx_; }
    set {
      behaviorIdx_ = value;
    }
  }

  /// <summary>Field number for the "params" field.</summary>
  public const int ParamsFieldNumber = 3;
  private pb::ByteString params_ = pb::ByteString.Empty;
  /// <summary>
  /// 参数
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Params {
    get { return params_; }
    set {
      params_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as FrameRpc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(FrameRpc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MethodHash != other.MethodHash) return false;
    if (BehaviorIdx != other.BehaviorIdx) return false;
    if (Params != other.Params) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (MethodHash != 0) hash ^= MethodHash.GetHashCode();
    if (BehaviorIdx != 0) hash ^= BehaviorIdx.GetHashCode();
    if (Params.Length != 0) hash ^= Params.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MethodHash != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(MethodHash);
    }
    if (BehaviorIdx != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(BehaviorIdx);
    }
    if (Params.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(Params);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MethodHash != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(MethodHash);
    }
    if (BehaviorIdx != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(BehaviorIdx);
    }
    if (Params.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(Params);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (MethodHash != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MethodHash);
    }
    if (BehaviorIdx != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BehaviorIdx);
    }
    if (Params.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Params);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(FrameRpc other) {
    if (other == null) {
      return;
    }
    if (other.MethodHash != 0) {
      MethodHash = other.MethodHash;
    }
    if (other.BehaviorIdx != 0) {
      BehaviorIdx = other.BehaviorIdx;
    }
    if (other.Params.Length != 0) {
      Params = other.Params;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          MethodHash = input.ReadInt32();
          break;
        }
        case 16: {
          BehaviorIdx = input.ReadInt32();
          break;
        }
        case 26: {
          Params = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          MethodHash = input.ReadInt32();
          break;
        }
        case 16: {
          BehaviorIdx = input.ReadInt32();
          break;
        }
        case 26: {
          Params = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
